# Generated by Django 5.0.7 on 2024-08-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicalBlog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="category",
        ),
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.ManyToManyField(
                blank=True, null=True, to="medicalBlog.category"
            ),
        ),
    ]
