# Generated by Django 5.0.7 on 2024-08-01 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicalBlog", "0002_remove_blog_category_blog_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="category",
        ),
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="medicalBlog.category",
            ),
        ),
    ]
