# Generated by Django 5.0.7 on 2024-08-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicalBlog", "0003_remove_blog_category_blog_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="draft",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
