# Generated by Django 5.0.7 on 2024-08-01 08:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0004_alter_profile_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialty",
            fields=[
                ("name", models.CharField(max_length=50)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        limit_choices_to={"account_user_type": "doctor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.profile",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="appointmentScheduler.specialty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"account_user_type": "patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.profile",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointmentScheduler.doctor",
                    ),
                ),
            ],
        ),
    ]
