# Generated by Django 5.0.7 on 2024-08-01 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointmentScheduler", "0002_auto_20240801_1420"),
    ]

    operations = []
