# Generated by Django 5.0.7 on 2024-08-01 17:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointmentScheduler", "0003_auto_20240801_1431"),
        ("users", "0004_alter_profile_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="specialty",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="users.profile",
            ),
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="date",
            new_name="appointment_date",
        ),
        migrations.AddField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="specialty",
            field=models.CharField(default="General", max_length=200),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="end_time",
            field=models.TimeField(editable=False),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booked_appointments",
                to="users.profile",
            ),
        ),
        migrations.DeleteModel(
            name="Specialty",
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
    ]
