# Generated by Django 5.0.7 on 2024-08-01 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointmentScheduler", "0005_alter_appointment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
